require('dotenv').config();
const express=require('express');
const cors=require('cors');
const jwt=require('jsonwebtoken');
const crypto=require('crypto');
const fs=require('fs');
const path=require('path');
const multer=require('multer');
const {Pool}=require('pg');
const {v2:cloudinary}=require('cloudinary');

const app=express();
const PORT=Number(process.env.PORT||5000);
const SECRET=process.env.JWT_SECRET||'change-me';
const DATA=path.join(__dirname,'..','data');
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024}});
app.use(cors({origin:(process.env.CORS_ORIGIN||'*').split(',').map(s=>s.trim())}));
app.use(express.json({limit:'2mb'}));
const fp=n=>path.join(DATA,n);
const read=n=>{try{return JSON.parse(fs.readFileSync(fp(n),'utf8'))}catch{return []}};
const write=(n,x)=>fs.writeFileSync(fp(n),JSON.stringify(x,null,2));
const id=p=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
const appId=()=>`AZK-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;
const hash=p=>crypto.createHash('sha256').update(p).digest('hex');
const slugify=s=>String(s||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||id('item');
const ROLES={
 super_admin:{label:'Super Administrator',permissions:['dashboard','admissions','inquiries','news','gallery','media','users','settings']},
 administrator:{label:'Administrator',permissions:['dashboard','admissions','inquiries','news','gallery','media','users']},
 admissions_officer:{label:'Admissions Officer',permissions:['dashboard','admissions','inquiries']},
 academic_officer:{label:'Academic Officer',permissions:['dashboard','news']},
 content_editor:{label:'Content Editor',permissions:['dashboard','news','settings']},
 gallery_manager:{label:'Gallery & Media Manager',permissions:['dashboard','gallery','media']},
 communications_officer:{label:'Communications Officer',permissions:['dashboard','news','inquiries','media']},
 viewer:{label:'Portal Viewer',permissions:['dashboard']}
};
let pool=null;
if(process.env.DATABASE_URL)pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes('localhost')?false:{rejectUnauthorized:false}});
async function dbReady(){
 if(!pool)return false;
 await pool.query(`CREATE TABLE IF NOT EXISTS content_news(id TEXT PRIMARY KEY,slug TEXT UNIQUE NOT NULL,title TEXT NOT NULL,category TEXT NOT NULL DEFAULT 'Institution',date_label TEXT NOT NULL,date DATE NOT NULL,excerpt TEXT NOT NULL,body TEXT DEFAULT '',image_url TEXT DEFAULT '',published BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS gallery_items(id TEXT PRIMARY KEY,title TEXT NOT NULL,category TEXT NOT NULL DEFAULT 'School Life',image_url TEXT NOT NULL,alt TEXT DEFAULT '',caption TEXT DEFAULT '',sort_order INTEGER NOT NULL DEFAULT 0,published BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS admissions(id TEXT PRIMARY KEY,application_id TEXT UNIQUE NOT NULL,name TEXT NOT NULL,phone TEXT NOT NULL,email TEXT DEFAULT '',programme TEXT NOT NULL,guardian TEXT DEFAULT '',previous_level TEXT DEFAULT '',message TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'received',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS inquiries(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL,subject TEXT NOT NULL,message TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'new',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'viewer',active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS site_settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);`);
 const count=await pool.query('SELECT COUNT(*)::int AS n FROM users');
 if(count.rows[0].n===0)for(const u of read('users.json'))await pool.query('INSERT INTO users(id,name,email,password_hash,role,active) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING',[u.id,u.name,u.email,u.passwordHash,u.role||'administrator',u.active!==false]);
 const newsCount=await pool.query('SELECT COUNT(*)::int AS n FROM content_news');
 if(newsCount.rows[0].n===0)for(const n of read('news.json'))await pool.query('INSERT INTO content_news(id,slug,title,category,date_label,date,excerpt,body,image_url,published) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT DO NOTHING',[id('news'),n.slug,n.title,n.category,n.dateLabel,n.date,n.excerpt,n.body||'',n.imageUrl||'',n.published!==false]);
 return true;
}
async function rows(sql,args=[]){return(await pool.query(sql,args)).rows}
async function allNews(){if(pool)return rows('SELECT id,slug,title,category,date_label AS "dateLabel",date,excerpt,body,image_url AS "imageUrl",published FROM content_news WHERE published=true ORDER BY date DESC,created_at DESC');return read('news.json').filter(x=>x.published!==false).sort((a,b)=>String(b.date).localeCompare(String(a.date)))}
async function allGallery(){if(pool)return rows('SELECT id,title,category,image_url AS "imageUrl",alt,caption,sort_order AS "sortOrder",published FROM gallery_items WHERE published=true ORDER BY sort_order ASC,created_at DESC');return read('gallery.json').filter(x=>x.published!==false).sort((a,b)=>(a.sortOrder||0)-(b.sortOrder||0))}
async function seedGallery(){if(!pool)return;const c=await pool.query('SELECT COUNT(*)::int AS n FROM gallery_items');if(c.rows[0].n===0)for(const g of read('gallery.json'))await pool.query('INSERT INTO gallery_items(id,title,category,image_url,alt,caption,sort_order,published) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT DO NOTHING',[g.id||id('gal'),g.title,g.category||'School Life',g.imageUrl,g.alt||'',g.caption||'',g.sortOrder||0,g.published!==false])}
async function seedSettings(){if(!pool)return;const settings={school_name:'Az-Zumratul Adabiyyatul Kamaliyyah',descriptor:'School for Arabic and Islamic Studies',location:'Okekere, Ilorin, Kwara State, Nigeria',hero_image:'',phone:'',whatsapp:'',email:'',mission:'Learning with knowledge, character and purpose.'};for(const[k,v]of Object.entries(settings))await pool.query('INSERT INTO site_settings(key,value) VALUES($1,$2) ON CONFLICT DO NOTHING',[k,v])}
async function init(){try{await dbReady();await seedGallery();await seedSettings();console.log(pool?'PostgreSQL ready':'JSON storage active')}catch(e){console.error('Database startup error:',e.message)}}init();
function auth(req,res,next){const h=req.headers.authorization||'',t=h.startsWith('Bearer ')?h.slice(7):null;if(!t)return res.status(401).json({message:'Authentication required'});try{req.user=jwt.verify(t,SECRET);next()}catch{return res.status(401).json({message:'Invalid or expired token'})}}
function allow(permission){return(req,res,next)=>{if(!ROLES[req.user?.role]?.permissions.includes(permission))return res.status(403).json({message:'You do not have permission for this module.'});next()}}
function admin(req,res,next){if(!ROLES[req.user?.role])return res.status(403).json({message:'Administrator access required'});next()}
async function getNewsById(idv){if(pool){const r=await rows('SELECT id,slug,title,category,date_label AS "dateLabel",date,excerpt,body,image_url AS "imageUrl",published FROM content_news WHERE id=$1',[idv]);return r[0]}return read('news.json').find(x=>x.id===idv)}
async function getGalleryById(idv){if(pool){const r=await rows('SELECT id,title,category,image_url AS "imageUrl",alt,caption,sort_order AS "sortOrder",published FROM gallery_items WHERE id=$1',[idv]);return r[0]}return read('gallery.json').find(x=>x.id===idv)}
app.get('/api/health',(q,s)=>s.json({ok:true,service:'az-zumratul-adabiyyatul-kamaliyyah-api'}));
app.get('/api/site/overview',(q,s)=>s.json({institution:{name:'Az-Zumratul Adabiyyatul Kamaliyyah',descriptor:'School for Arabic and Islamic Studies',location:'Okekere, Ilorin, Kwara State, Nigeria'},levels:['Tamheediyyah','Ibtidā’iyyah','Ihdādiyyah','Thanawiyyah']}));
app.get('/api/news',async(q,s)=>s.json({items:await allNews()}));
app.get('/api/gallery',async(q,s)=>s.json({items:await allGallery()}));
app.get('/api/site/settings',async(q,s)=>{if(pool){const r=await rows('SELECT key,value FROM site_settings');return s.json({settings:Object.fromEntries(r.map(x=>[x.key,x.value]))})}s.json({settings:{school_name:'Az-Zumratul Adabiyyatul Kamaliyyah',descriptor:'School for Arabic and Islamic Studies',location:'Okekere, Ilorin, Kwara State, Nigeria',hero_image:'',phone:'',whatsapp:'',email:'',mission:'Learning with knowledge, character and purpose.'}})});
app.post('/api/admissions',async(req,res)=>{const{name,phone,email='',programme,guardian='',previousLevel='',message=''}=req.body||{};if(!name||!phone||!programme)return res.status(400).json({message:'Name, phone and level are required.'});const applicationId=appId(),rid=id('adm');if(pool)await pool.query('INSERT INTO admissions(id,application_id,name,phone,email,programme,guardian,previous_level,message) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[rid,applicationId,name,phone,email,programme,guardian,previousLevel,message]);else{const items=read('admissions.json');items.push({id:rid,applicationId,name,phone,email,programme,guardian,previousLevel,message,status:'received',createdAt:new Date().toISOString()});write('admissions.json',items)}res.status(201).json({ok:true,applicationId})});
app.post('/api/inquiries',async(req,res)=>{const{name,email,subject,message}=req.body||{};if(!name||!email||!subject||!message)return res.status(400).json({message:'Name, email, subject and message are required.'});const rid=id('inq');if(pool)await pool.query('INSERT INTO inquiries(id,name,email,subject,message) VALUES($1,$2,$3,$4,$5)',[rid,name,email,subject,message]);else{const items=read('inquiries.json');items.push({id:rid,name,email,subject,message,status:'new',createdAt:new Date().toISOString()});write('inquiries.json',items)}res.status(201).json({ok:true})});
app.post('/api/auth/login',async(req,res)=>{const{email,password}=req.body||{};if(!email||!password)return res.status(400).json({message:'Email and password are required.'});let user;if(pool){const r=await rows('SELECT id,name,email,password_hash AS "passwordHash",role,active FROM users WHERE LOWER(email)=LOWER($1)',[email]);user=r[0]}else user=read('users.json').find(u=>u.email.toLowerCase()===email.toLowerCase());if(!user||user.active===false||hash(password)!==user.passwordHash)return res.status(401).json({message:'Invalid email or password.'});const token=jwt.sign({sub:user.id,name:user.name,email:user.email,role:user.role},SECRET,{expiresIn:'8h'});res.json({token,user:{id:user.id,name:user.name,email:user.email,role:user.role,roleLabel:ROLES[user.role]?.label||user.role,permissions:ROLES[user.role]?.permissions||[]}})});
async function fetchStats(){const a=pool?(await rows('SELECT COUNT(*)::int AS n FROM admissions'))[0].n:read('admissions.json').length;const i=pool?(await rows("SELECT COUNT(*)::int AS n FROM inquiries WHERE status='new'"))[0].n:read('inquiries.json').filter(x=>x.status==='new').length;const n=pool?(await rows('SELECT COUNT(*)::int AS n FROM content_news WHERE published=true'))[0].n:read('news.json').filter(x=>x.published!==false).length;const g=pool?(await rows('SELECT COUNT(*)::int AS n FROM gallery_items WHERE published=true'))[0].n:read('gallery.json').filter(x=>x.published!==false).length;const u=pool?(await rows('SELECT COUNT(*)::int AS n FROM users WHERE active=true'))[0].n:read('users.json').filter(x=>x.active!==false).length;return{total_users:u,applications_received:a,new_inquiries:i,published_news:n,gallery_items:g}}
app.get('/api/admin/bootstrap',auth,admin,async(req,res)=>res.json({user:{...req.user,roleLabel:ROLES[req.user.role].label,permissions:ROLES[req.user.role].permissions},stats:await fetchStats(),roles:ROLES}));
app.get('/api/admin/stats',auth,allow('dashboard'),async(req,res)=>res.json({stats:await fetchStats()}));
app.get('/api/admin/admissions',auth,allow('admissions'),async(req,res)=>{const items=pool?await rows('SELECT id,application_id AS "applicationId",name,phone,email,programme,guardian,previous_level AS "previousLevel",message,status,created_at AS "createdAt" FROM admissions ORDER BY created_at DESC'):read('admissions.json').sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));res.json({items})});
app.patch('/api/admin/admissions/:id',auth,allow('admissions'),async(req,res)=>{const status=String(req.body?.status||'').trim();if(!['received','under_review','accepted','waitlisted','rejected','completed'].includes(status))return res.status(400).json({message:'Invalid admission status.'});if(pool)await pool.query('UPDATE admissions SET status=$1,updated_at=NOW() WHERE id=$2',[status,req.params.id]);else{const items=read('admissions.json'),x=items.find(i=>i.id===req.params.id);if(!x)return res.status(404).json({message:'Application not found'});x.status=status;write('admissions.json',items)}res.json({ok:true})});
app.get('/api/admin/inquiries',auth,allow('inquiries'),async(req,res)=>{const items=pool?await rows('SELECT id,name,email,subject,message,status,created_at AS "createdAt" FROM inquiries ORDER BY created_at DESC'):read('inquiries.json').sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));res.json({items})});
app.patch('/api/admin/inquiries/:id',auth,allow('inquiries'),async(req,res)=>{const status=String(req.body?.status||'').trim();if(!['new','read','replied','archived'].includes(status))return res.status(400).json({message:'Invalid inquiry status.'});if(pool)await pool.query('UPDATE inquiries SET status=$1,updated_at=NOW() WHERE id=$2',[status,req.params.id]);else{const items=read('inquiries.json'),x=items.find(i=>i.id===req.params.id);if(!x)return res.status(404).json({message:'Inquiry not found'});x.status=status;write('inquiries.json',items)}res.json({ok:true})});
app.get('/api/admin/news',auth,allow('news'),async(req,res)=>res.json({items:pool?await rows('SELECT id,slug,title,category,date_label AS "dateLabel",date,excerpt,body,image_url AS "imageUrl",published FROM content_news ORDER BY date DESC,created_at DESC'):read('news.json')}));
app.post('/api/admin/news',auth,allow('news'),async(req,res)=>{const b=req.body||{};if(!b.title||!b.excerpt)return res.status(400).json({message:'Title and excerpt are required.'});const rid=id('news'),slug=slugify(b.slug||b.title),date=b.date||new Date().toISOString().slice(0,10),dateLabel=b.dateLabel||new Date(date).toLocaleDateString('en-US',{month:'long',year:'numeric'});if(pool)await pool.query('INSERT INTO content_news(id,slug,title,category,date_label,date,excerpt,body,image_url,published) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[rid,slug,b.title,b.category||'Institution',dateLabel,date,b.excerpt,b.body||'',b.imageUrl||'',b.published!==false]);else{const items=read('news.json');items.unshift({id:rid,slug,title:b.title,category:b.category||'Institution',dateLabel,date,excerpt:b.excerpt,body:b.body||'',imageUrl:b.imageUrl||'',published:b.published!==false});write('news.json',items)}res.status(201).json({ok:true,id:rid})});
app.patch('/api/admin/news/:id',auth,allow('news'),async(req,res)=>{const b=req.body||{},old=await getNewsById(req.params.id);if(!old)return res.status(404).json({message:'News item not found'});const x={...old,...b,slug:slugify(b.slug||old.slug)};if(pool)await pool.query('UPDATE content_news SET slug=$1,title=$2,category=$3,date_label=$4,date=$5,excerpt=$6,body=$7,image_url=$8,published=$9,updated_at=NOW() WHERE id=$10',[x.slug,x.title,x.category,x.dateLabel,x.date,x.excerpt,x.body||'',x.imageUrl||'',x.published!==false,req.params.id]);else{const items=read('news.json'),i=items.findIndex(v=>v.id===req.params.id);items[i]=x;write('news.json',items)}res.json({ok:true})});
app.delete('/api/admin/news/:id',auth,allow('news'),async(req,res)=>{if(pool)await pool.query('DELETE FROM content_news WHERE id=$1',[req.params.id]);else write('news.json',read('news.json').filter(x=>x.id!==req.params.id));res.json({ok:true})});
app.get('/api/admin/gallery',auth,allow('gallery'),async(req,res)=>res.json({items:pool?await rows('SELECT id,title,category,image_url AS "imageUrl",alt,caption,sort_order AS "sortOrder",published FROM gallery_items ORDER BY sort_order ASC,created_at DESC'):read('gallery.json')}));
app.post('/api/admin/gallery',auth,allow('gallery'),async(req,res)=>{const b=req.body||{};if(!b.title||!b.imageUrl)return res.status(400).json({message:'Title and image URL are required.'});const rid=id('gal');if(pool)await pool.query('INSERT INTO gallery_items(id,title,category,image_url,alt,caption,sort_order,published) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[rid,b.title,b.category||'School Life',b.imageUrl,b.alt||b.title,b.caption||'',Number(b.sortOrder||0),b.published!==false]);else{const items=read('gallery.json');items.push({id:rid,title:b.title,category:b.category||'School Life',imageUrl:b.imageUrl,alt:b.alt||b.title,caption:b.caption||'',sortOrder:Number(b.sortOrder||0),published:b.published!==false});write('gallery.json',items)}res.status(201).json({ok:true,id:rid})});
app.patch('/api/admin/gallery/:id',auth,allow('gallery'),async(req,res)=>{const b=req.body||{},old=await getGalleryById(req.params.id);if(!old)return res.status(404).json({message:'Gallery item not found'});const x={...old,...b};if(pool)await pool.query('UPDATE gallery_items SET title=$1,category=$2,image_url=$3,alt=$4,caption=$5,sort_order=$6,published=$7,updated_at=NOW() WHERE id=$8',[x.title,x.category,x.imageUrl,x.alt||x.title,x.caption||'',Number(x.sortOrder||0),x.published!==false,req.params.id]);else{const items=read('gallery.json'),i=items.findIndex(v=>v.id===req.params.id);items[i]=x;write('gallery.json',items)}res.json({ok:true})});
app.delete('/api/admin/gallery/:id',auth,allow('gallery'),async(req,res)=>{if(pool)await pool.query('DELETE FROM gallery_items WHERE id=$1',[req.params.id]);else write('gallery.json',read('gallery.json').filter(x=>x.id!==req.params.id));res.json({ok:true})});
app.post('/api/admin/media/upload',auth,allow('media'),upload.single('image'),async(req,res)=>{if(!req.file)return res.status(400).json({message:'Choose an image file.'});if(!process.env.CLOUDINARY_CLOUD_NAME||!process.env.CLOUDINARY_API_KEY||!process.env.CLOUDINARY_API_SECRET)return res.status(503).json({message:'Image uploads are not configured yet. Add CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET in Render, or paste an image URL.'});cloudinary.config({cloud_name:process.env.CLOUDINARY_CLOUD_NAME,api_key:process.env.CLOUDINARY_API_KEY,api_secret:process.env.CLOUDINARY_API_SECRET});try{const result=await new Promise((resolve,reject)=>{const stream=cloudinary.uploader.upload_stream({folder:'az-zumratul-adabiyyatul-kamaliyyah'},(e,r)=>e?reject(e):resolve(r));stream.end(req.file.buffer)});res.json({ok:true,url:result.secure_url,publicId:result.public_id,width:result.width,height:result.height})}catch(e){res.status(500).json({message:'Image upload failed: '+e.message})}});
app.get('/api/admin/users',auth,allow('users'),async(req,res)=>{const items=pool?await rows('SELECT id,name,email,role,active,created_at AS "createdAt" FROM users ORDER BY created_at DESC'):read('users.json').map(({passwordHash,...u})=>u);res.json({items})});
app.post('/api/admin/users',auth,allow('users'),async(req,res)=>{const b=req.body||{};if(!b.name||!b.email||!b.password||!ROLES[b.role])return res.status(400).json({message:'Name, email, password and a valid role are required.'});const rid=id('usr');if(pool)await pool.query('INSERT INTO users(id,name,email,password_hash,role,active) VALUES($1,$2,$3,$4,$5,$6)',[rid,b.name,b.email,hash(b.password),b.role,b.active!==false]);else{const items=read('users.json');if(items.some(x=>x.email.toLowerCase()===b.email.toLowerCase()))return res.status(409).json({message:'Email already exists.'});items.push({id:rid,name:b.name,email:b.email,passwordHash:hash(b.password),role:b.role,active:b.active!==false});write('users.json',items)}res.status(201).json({ok:true,id:rid})});
app.patch('/api/admin/users/:id',auth,allow('users'),async(req,res)=>{const b=req.body||{};if(b.role&&!ROLES[b.role])return res.status(400).json({message:'Invalid role.'});if(pool){if(b.password)await pool.query('UPDATE users SET name=COALESCE($1,name),email=COALESCE($2,email),role=COALESCE($3,role),active=COALESCE($4,active),password_hash=$5 WHERE id=$6',[b.name,b.email,b.role,b.active,hash(b.password),req.params.id]);else await pool.query('UPDATE users SET name=COALESCE($1,name),email=COALESCE($2,email),role=COALESCE($3,role),active=COALESCE($4,active) WHERE id=$5',[b.name,b.email,b.role,b.active,req.params.id])}else{const items=read('users.json'),x=items.find(i=>i.id===req.params.id);if(!x)return res.status(404).json({message:'User not found'});Object.assign(x,{name:b.name??x.name,email:b.email??x.email,role:b.role??x.role,active:b.active??x.active});if(b.password)x.passwordHash=hash(b.password);write('users.json',items)}res.json({ok:true})});
app.delete('/api/admin/users/:id',auth,allow('users'),async(req,res)=>{if(req.params.id===req.user.sub)return res.status(400).json({message:'You cannot delete your own account.'});if(pool)await pool.query('DELETE FROM users WHERE id=$1',[req.params.id]);else write('users.json',read('users.json').filter(x=>x.id!==req.params.id));res.json({ok:true})});
app.put('/api/admin/settings',auth,allow('settings'),async(req,res)=>{const allowed=['school_name','descriptor','location','hero_image','phone','whatsapp','email','mission'];const entries=Object.entries(req.body||{}).filter(([k])=>allowed.includes(k));if(pool)for(const[k,v]of entries)await pool.query('INSERT INTO site_settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value',[k,String(v??'')]);res.json({ok:true})});
app.use((q,s)=>s.status(404).json({message:'Route not found'}));
app.listen(PORT,()=>console.log(`API running on port ${PORT}`));